 language: CSharp
 mono:
   - latest 
 install:
   - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh 
   - dnvm upgrade 
   - dnu restore 
 script: 
   - dnx -p Test/project.json test -parallel none